apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-secret
spec:
  encryptedData:
    password: AgA2F3bl7o8m56YjjHcu+o81MVwe8pH1o2/PAVhz5C7PgFWP/SH9t+X2hUH09R0rZsRfATMSpP0YTLEBVbRq89Lig2ODsm5eZLONZ/MjBNBFnz19DmbK55d5kDd4h6Shk0ZOJiXaoIIVaEl/Kwol1jMyJdbu1s3IJg5kyNol2QaNMDihcBJtgm1nwVol7xpQ0YhW7upvUIMWgY3/rW/CQ1h2G1IFQ2kJ5cE39iCvFc5sWjE+GEeqq1zVpqqHfsO2/nC6dOa1by6+gKUW1Z/PypRShaDwIOYgT8Ez5ZzFPr1sYZGgLiV6KkzwA2+ZLVEh4mohGM5AiMyhf3gSMqkbs5bcWwL4tdt2bTEyxmJQ5WOGrL2nGBMyE+NecwWxJC+3Oc+0fCP0GrbB+dYp7T5lsNoAZsaCk924yGED9iig7KwiWplJaU0atDZLUQ5CeBeRweo26YtUnlT8tivrE6L5XvqMkxcfx0baLnctW6huZmym16tJ8lqkCR5aDpQVjWfIJ6csmzUo2suvjJQiykuvi/dkaEGwZYbte+MXhOffhC00/YPbP4cXckdCY2IgomwZ1L4k293/Bb4lIPjtVBmeJb9+sKhUwiHJpq/ELsrEYkG4Q68KWBzRcibjxNTH+jRSg2TBSz1PgBubfQ8KicWV8WHmwhX70L0z3vHwx3+m9W7HbiCE9x+ey9vy6f7JxG5TyvzJa0ieXPoyO8k4Jw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-secret
