apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-secret
  namespace: default
spec:
  encryptedData:
    password: AgBrv9WAeibGC2U2OT6dWY8lWlqCNN95/D/iGd70BRDyo785Hc8GSVr5Dg1tVGlWCV3erMLyqjhyWyjUOXb40ZqdqrfiaVutMiAWkB0AFWR4OTuMz3ZDjhd8aLzeIhjwb9EZGgk1sZq9Y0HpHD0Jee6i60uz/Ibs0glWW+A1D1+ANf4dfzHTgb1bo1xAB1N3qRkvhY/MLeCw18sqSq24QT2IzoF8An5kMrFvfNrEHhz4w24Ci0rDkiueEyqWAk0Qu2SphGPEP5iZpYAhqG2gcgiqTaeOOFpKX+3IqvYAOtFk7z0eLDtX/tNL6b9YYW7BnR4SYtS6sdiQDJaQksv+fcKGOhjqmYQ1bXWJiWe+PU+ZKAhPhxVCmj6v2gKcKV7VNk6vI8ZXXnLl0lmfnuuy0Bevk0FT85TABHBFL6c3SpCxAfalXJiuK4j4LLh24sV1y8HHw+IDwIRxJUmTaKx12nyqC9fh602JmlOHziSXx8e7RTMSWexw1XMD+KzzQOW5cn+MqhYStqxgjc0Z7ZJSb5qmYywEDigj8QUJmYh078DxbOSyAzoDGfwAP3FPQoNz6ojNs29lHl8F0mGFkH/BlwYpchsZN6N8if6tN94m4vVlgSLP8fJDcg05q+2YBF8qNX5aeB8dRVfL9sXjbx1jxThhCHdET/bn3pRP1c9aVy6/0VQjUSJhE2Pog08e4VdFB/jzbgIVnlXSOCYo0NM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-secret
